### ISSUE TITLE
OO Support Guidelines

### ISSUE THREAD

**Issue by FilipToth** [AltoLang/Alto#55]
## Background and Motivation
It's no secret that every language is better with OO support. This will also be super useful when writing the runtime API.

## TODO

- [ ] Parse class declarations 
- [ ] Bind class declarations
- [ ] Parse constructors
- [ ] Bind constructors
- [ ] Parse class references
- [ ] Bind class references
- [ ] Parse namespace declarations
- [ ] Bind namespace declarations
- [ ] Parse namespace references
- [ ] Bind namespace references
- [ ] Make `import` statements import namespaces not files
- [ ] Add `private`, `internal`, and `public` accessors
- [ ] Support static classes (Will be called `objectgroup`)
     
## Syntax
```ts
namespace MyLib {
    public class MyClass {
        private _number : int = 0

        public function addToNumber(addend : int) {
            _number = _number + addend
        }

        public function getNumber() : int {
            return _number
        }
    }
}
```
