### ISSUE TITLE
IL-Gen Mega Issue

### ISSUE THREAD

**Issue by FilipToth** [AltoLang/Alto#81]
**This issue will track everything we need to do to fully emit IL.**

## TODO

- [x] Function declarations
- [x] Function calls
- [x] Return statements
- [x] Parameters
- [x] Builtin: Print
- [x] Builtin: ReadLine
- [x] Builtin: Random
- [x] Variable declarations
- [x] Variable  expression
- [x] Literals
- [x] Locals
- [x] Assignments
- [x] String Concatenation
- [x] Integer binary operations
- [x] Boolean binary operations
- [x] String binary operations
- [x] Integer unary operations
- [x] Boolean unary operations
- [x] String unary operations
- [x] Conversion expressions
- [x] GOTOs
- [x] Conditional GOTOs
- [x] Labels

## PRs
 - #77 
 - #78 
- #85
